<?php

    error_reporting(E_ALL);
    ini_set("display_errors", 1);

class JConfig {
	public $MetaAuthor = '0';
	public $MetaDesc = '';
	public $MetaKeys = '';
	public $MetaRights = '';
	public $MetaTitle = '1';
	public $MetaVersion = '0';
	public $access = '1';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $caching = '0';
	public $captcha = 'recaptcha';
	public $cookie_domain = '';
	public $cookie_path = '';
	public $db = 'heroku_8990b54bcad09dc';
	public $dbprefix = 'prm_';
	public $dbtype = 'mysqli';
	public $debug = '1';
	public $debug_lang = '0';
	public $display_offline_message = '1';
	public $editor = 'tinymce';
	public $error_reporting = 'none';
	public $feed_email = 'author';
	public $feed_limit = '10';
	public $force_ssl = '0';
	public $fromname = 'BB Ninja';
	public $ftp_enable = '0';
	public $ftp_host = '127.0.0.1';
	public $ftp_pass = '';
	public $ftp_port = '21';
	public $ftp_root = '';
	public $ftp_user = '';
	public $gzip = '0';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $host = 'us-cdbr-iron-east-03.cleardb.net';
	public $lifetime = '9999';
	public $list_limit = '20';
	public $live_site = '';
	public $log_path = '/nfs/c04/h03/mnt/60664/domains/bbninjaalpha.pantilla.com/html/log';
	public $mailer = 'mail';
	public $mailfrom = 'support@bbninja.com';
	public $memcache_compress = '1';
	public $memcache_persist = '1';
	public $memcache_server_host = 'us-cdbr-iron-east-03.cleardb.net';
	public $memcache_server_port = '11211';
	public $offline = '0';
	public $offline_image = '';
	public $offline_message = 'This site is down for maintenance.<br /> Please check back again soon.';
	public $offset = 'UTC';
	public $offset_user = 'UTC';
	public $password = 'e7130233';
	public $robots = '';
	public $secret = 'HneOZwMIo0ItNs0UmyQZH5lQA3WVBJEC';
	public $sef = '1';
	public $sef_rewrite = '0';
	public $sef_suffix = '0';
	public $sendmail = '/usr/sbin/sendmail';
	public $session_handler = 'database';
	public $sitename = 'BB Ninja';
	public $sitename_pagetitles = '1';
	public $smtpauth = '0';
	public $smtphost = 'localhost';
	public $smtppass = '';
	public $smtpport = '25';
	public $smtpsecure = 'none';
	public $smtpuser = '';
	public $tmp_path = './html/tmp';
	public $unicodeslugs = '0';
	public $user = 'bf4ef58d12dbab';
	public $mailonline = '1';
	public $frontediting = '1';
	public $asset_id = '1';
}